default: &default
  adapter: postgresql
  encoding: unicode
  database: receipt-transcriber
  pool: 5
  username:
  password:
  timeout: 5000


development:
  <<: *default
  database: development-receipt-transcriber

test:
  <<: *default
  database: test-receipt-transcriber

production:
  <<: *default
  database: production-receipt-transcriber